### ISSUE TITLE
Пример CSV

### ISSUE THREAD

**Issue by aspayr** [MironLeonov/csv_to_yml#1]
Подскажите пожалуйста, есть ли у вас пример корректного CSV файла для успешной конвертации в YML?

Заранее благодарен!)

**Comment by MironLeonov** [comment]
Здравствуйте! 

Небольшой пример: https://drive.google.com/file/d/1kyAevkQWNphO4X-zwia5V7rhdk1ZsOgN/view?usp=sharing

**Comment by aspayr** [comment]
> Здравствуйте!
> 
> Небольшой пример: https://drive.google.com/file/d/1kyAevkQWNphO4X-zwia5V7rhdk1ZsOgN/view?usp=sharing

Спасибо :)
